---
$ oc get policy compliance-operator -o yaml
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous
      Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
  generation: 14
  name: compliance-operator
  namespace: cluster-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: comp-operator-ns
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: openshift-compliance
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: bob
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: bob
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1beta1
      kind: OperatorPolicy
      metadata:
        name: operatorpolicy-comp-operator
      spec:
        complianceType: musthave
        operatorGroup:
          name: compliance-operator
          namespace: openshift-compliance
          targetNamespaces:
          - openshift-compliance
        remediationAction: enforce
        severity: high
        subscription:
          config: '{{ if and (eq "ROSA" (fromClusterClaim "product.open-cluster-management.io"))
            (eq "true" (fromClusterClaim "hostedcluster.hypershift.openshift.io"))
            }}{"nodeSelector":{"node-role.kubernetes.io/worker":""} }{{ else }}{{
            "{}" | toLiteral }}{{ end }}'
          name: compliance-operator
          namespace: openshift-compliance
          source: redhat-operators
          sourceNamespace: openshift-marketplace
        upgradeApproval: Automatic
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: scansetting-default
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: compliance.openshift.io/v1alpha1
            autoApplyRemediations: false
            kind: ScanSetting
            metadata:
              name: default-scan
              namespace: openshift-compliance
            rawResultStorage:
              nodeSelector:
                node-role.kubernetes.io/worker: ""
              pvAccessModes:
              - ReadWriteOnce
              rotation: 5
              size: 5Gi
            roles:
            - worker
            schedule: '*/5 * * * *'
        remediationAction: enforce
        severity: high


---
$ oc get placements  compliance-operator-placement -o yaml
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: compliance-operator-placement
  namespace: cluster-policies
spec:
  clusterSets:
  - global
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists

---
$ oc get placementbinding compliance-operator-placement -o yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  generation: 1
  name: compliance-operator-placement
  namespace: cluster-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: compliance-operator-placement
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: compliance-operator
